/**
 * Team colours, keyed by nflverse abbreviation.
 *
 * Adapted from the fanbank palette. These live in the repository rather than
 * being read from index.json because index.json is regenerated by the R
 * pipeline from `nflreadr::load_teams()`, whose primaries are a different
 * editorial choice on several teams — Pittsburgh, New Orleans and
 * Jacksonville most visibly. The index values stay as a fallback so a team
 * that is missing here still renders.
 *
 * nflverse abbreviates Jacksonville JAX and the Rams LA; the source palette
 * uses JAC and LAR.
 *
 * Two secondaries differ from the source, both because a black accent is
 * invisible against the primary it has to sit on: Baltimore uses its gold
 * rather than black on purple, and the Jets use white rather than black on
 * green. Both are the team's own colours.
 */
export interface TeamPalette {
  primary: string
  secondary: string
}

export const TEAM_COLORS: Record<string, TeamPalette> = {
  // AFC East
  BUF: { primary: '#00338D', secondary: '#C60C30' },
  MIA: { primary: '#008E97', secondary: '#FC4C02' },
  NE: { primary: '#002244', secondary: '#C60C30' },
  NYJ: { primary: '#125740', secondary: '#FFFFFF' },

  // AFC North
  BAL: { primary: '#241773', secondary: '#9E7C0C' },
  CIN: { primary: '#FB4F14', secondary: '#000000' },
  CLE: { primary: '#311D00', secondary: '#FF3C00' },
  PIT: { primary: '#FFB612', secondary: '#000000' },

  // AFC South
  HOU: { primary: '#03202F', secondary: '#A71930' },
  IND: { primary: '#002C5F', secondary: '#A2AAAD' },
  JAX: { primary: '#101820', secondary: '#D7A22A' },
  TEN: { primary: '#0C2340', secondary: '#4B92DB' },

  // AFC West
  DEN: { primary: '#FB4F14', secondary: '#002244' },
  KC: { primary: '#E31837', secondary: '#FFB81C' },
  LV: { primary: '#000000', secondary: '#A5ACAF' },
  LAC: { primary: '#0080C6', secondary: '#FFC20E' },

  // NFC East
  DAL: { primary: '#041E42', secondary: '#869397' },
  NYG: { primary: '#0B2265', secondary: '#A71930' },
  PHI: { primary: '#004C54', secondary: '#A5ACAF' },
  WAS: { primary: '#5A1414', secondary: '#FFB612' },

  // NFC North
  CHI: { primary: '#0B162A', secondary: '#C83803' },
  DET: { primary: '#0076B6', secondary: '#B0B7BC' },
  GB: { primary: '#203731', secondary: '#FFB612' },
  MIN: { primary: '#4F2683', secondary: '#FFC62F' },

  // NFC South
  ATL: { primary: '#A71930', secondary: '#000000' },
  CAR: { primary: '#0085CA', secondary: '#101820' },
  NO: { primary: '#101820', secondary: '#D3BC8D' },
  TB: { primary: '#D50A0A', secondary: '#FF7900' },

  // NFC West
  ARI: { primary: '#97233F', secondary: '#000000' },
  LA: { primary: '#003594', secondary: '#FFA300' },
  SF: { primary: '#AA0000', secondary: '#B3995D' },
  SEA: { primary: '#002244', secondary: '#69BE28' },
}
